### ISSUE TITLE
[minor] Usage of implicit return

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#10]
Remember to take advantage of this functionality when all the content of your arrow function is returned

https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/componentes/Content.tsx#L85

**Comment by Asturiana88** [comment]
Resolved in Issue-10 **Usage of implicit return baf38f2**
Implicit returns tidy up.
