### ISSUE TITLE
[minor] Cascading conditional renderings

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#11]
Prefer to use a returning function to handle all cases, and use `if` blocks

https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/componentes/Content.tsx#L88

**Comment by Asturiana88** [comment]
Resolved in Issue-11-17 **Cascading conditional renderings 96f631e**
