### ISSUE TITLE
[minor] Prefer template strings over the usage of string concatenation

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#12]
It is a cleaner approach to handle strings with variables

https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/componentes/Content.tsx#L90

**Comment by Asturiana88** [comment]
Resolved in **Issue12-19 Prefer template strings over the usage of string concatenat 9d99301**
