### ISSUE TITLE
[minor] Type validation

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#18]
You can use the `or` operator in this case, to handle both scenarios: `selElem.type || " - "`

https://github.com/Asturiana88/ReactJsChallenge/blob/0e40b8bbac6dcccf5b48d128663be3bbc1c7c6ce/src/components/Entity.tsx#L30

**Comment by Asturiana88** [comment]
Resolved in  **Issue-18 Type validation 49101a2**
