### ISSUE TITLE
[minor] Prefer template strings over the usage of string concatenation

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#19]
Check #12 

https://github.com/Asturiana88/ReactJsChallenge/blob/0e40b8bbac6dcccf5b48d128663be3bbc1c7c6ce/src/components/Entity.tsx#L48
https://github.com/Asturiana88/ReactJsChallenge/blob/0e40b8bbac6dcccf5b48d128663be3bbc1c7c6ce/src/components/Entity.tsx#L49
https://github.com/Asturiana88/ReactJsChallenge/blob/0e40b8bbac6dcccf5b48d128663be3bbc1c7c6ce/src/components/Entity.tsx#L58

**Comment by Asturiana88** [comment]
Resolved in **Issue12-19 Prefer template strings over the usage of string concatenat 9d99301**
