### ISSUE TITLE
[minor] Props & state naming

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#21]
As an internal guideline, what we do is the name the main component's Props & State by those general names

https://github.com/Asturiana88/ReactJsChallenge/blob/baf38f24dea4a4f8bf02641d06303565d22f4cbb/src/components/SideFilters.tsx#L3

**Comment by Asturiana88** [comment]
Resolved in **Issue-21 Props & state naming a9bdf7d**
