### ISSUE TITLE
[minor] Place styles on their own separated stylesheet

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#23]
https://github.com/Asturiana88/ReactJsChallenge/blob/baf38f24dea4a4f8bf02641d06303565d22f4cbb/src/components/SideFilters.tsx#L14
https://github.com/Asturiana88/ReactJsChallenge/blob/baf38f24dea4a4f8bf02641d06303565d22f4cbb/src/components/SideFilters.tsx#L25
https://github.com/Asturiana88/ReactJsChallenge/blob/baf38f24dea4a4f8bf02641d06303565d22f4cbb/src/components/SideFilters.tsx#L36

**Comment by Asturiana88** [comment]
Resolved in **Issue-23 Place styles on their own separated stylesheet 35b3e3a**
Replaces inline Styles with bootstrap classes.
