### ISSUE TITLE
[minor] State type

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#4]
Always declare the type of the state

https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/App.tsx#L17
https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/App.tsx#L18
https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/App.tsx#L19

**Comment by Asturiana88** [comment]
Resolved in Issue-4 **State type 295d9db**
Added missing types on useStates.
