### ISSUE TITLE
[minor] Props handling on functional component

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#7]
Destructure props on function argument, separate props interface externally of the function.

https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/componentes/Content.tsx#L28

**Comment by Asturiana88** [comment]
Resolved in **Issue-7 Props handling on functional component 0e40b8b**
Interface creation and props destructuring in function parameters.
