### ISSUE TITLE
[minor] State type

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#8]
Check #4 

https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/componentes/Content.tsx#L31
https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/componentes/Content.tsx#L32

**Comment by Asturiana88** [comment]
Already solved in **Issue-4 State type 295d9db**
Added missing types on useStates.
