### ISSUE TITLE
[minor] Use a single dynamic handler for prev & next

### ISSUE THREAD

**Issue by ale1313** [Asturiana88/ReactJsChallenge#9]
https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/componentes/Content.tsx#L66
https://github.com/Asturiana88/ReactJsChallenge/blob/50799c4aaa59c5be5b70312ab43e0735de0ab51b/src/componentes/Content.tsx#L70

**Comment by Asturiana88** [comment]
Resolved in **Issue-9 Use a single dynamic handler for prev & next 923c3ab**
Removes unnecessary function pageHandler.
